version: '3.9'
services:
  b007-empire:
    build: .
    container_name: b007-empire-2025
    ports:
      - "8000:8000"
    volumes:
      - ./sessions:/app/sessions
      - ./exports:/app/exports
      - ./avatars:/app/avatars
    env_file: .env
    restart: always